# Corrélations pour Sens Critique

Import des datasets

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('users_and_mean_rating.csv',low_memory=False)

## Normalisation du dataframe

In [4]:
df_normal = ((df-df.min())/(df.max()-df.min()))

In [5]:
df_normal

,Unnamed: 0,user_id,nb_eclaireurs,nb_suiveurs,nb_critiques,nb_notes,moyenne_notes
0,0.000000,0.000759,0.000201,0.000270,0.000000,0.000064,0.888889
1,0.000015,0.001407,0.000101,0.000000,0.000000,0.000064,0.777778
2,0.000029,0.001665,0.000101,0.000135,0.000000,0.000064,0.888889
3,0.000044,0.002024,0.000402,0.000405,0.000000,0.000064,0.555556
4,0.000059,0.002310,0.000101,0.000405,0.000000,0.000064,0.888889
...,...,...,...,...,...,...,...
67908,0.999941,0.024765,0.000000,0.000541,0.003491,0.150093,0.472744
67909,0.999956,0.067963,0.018098,0.005001,0.001204,0.164564,0.539689
67910,0.999971,0.176609,0.008848,0.092580,0.031295,0.428379,0.712224
67911,0.999985,0.055235,0.009753,0.084606,0.000602,0.399052,0.610558
67912,1.000000,0.205613,0.061231,0.217462,0.002167,0.177691,0.599399

## Calcul des corrélations

In [6]:
df_normal.corr()

,Unnamed: 0,user_id,nb_eclaireurs,nb_suiveurs,nb_critiques,nb_notes,moyenne_notes
Unnamed: 0,1.000000,-0.230149,0.231135,0.238665,0.170812,0.719529,-0.339994
user_id,-0.230149,1.000000,-0.071197,-0.122809,-0.068821,-0.192185,0.086131
nb_eclaireurs,0.231135,-0.071197,1.000000,0.198585,0.115419,0.246465,-0.076002
nb_suiveurs,0.238665,-0.122809,0.198585,1.000000,0.372435,0.444214,-0.095537
nb_critiques,0.170812,-0.068821,0.115419,0.372435,1.000000,0.305107,-0.076908
nb_notes,0.719529,-0.192185,0.246465,0.444214,0.305107,1.000000,-0.290569
moyenne_notes,-0.339994,0.086131,-0.076002,-0.095537,-0.076908,-0.290569,1.000000